### ISSUE TITLE
Adding a surface field to a VTK POLYDATA file with a surface field throws exception

### ISSUE THREAD

**Issue by gregvonkuster** [pletzer/icqsol#28]
The attached VTK file (I had to use a .txt extension so I could attach it here) is a composed shape created with our Galaxy tools and the icqsol package.  I added a single surface field (time point 0) to the composed shape using this expression: 

(x**2 * sin(y*pi) + z**4) * exp(t)

Attempting to add a second surface field using any expression, including the same expression above (but also random different expressions) always results in the following exception:

Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_add_surface_field_from_expression/a99185a97279/icqsol_add_surface_field_from_expression/icqsol_add_surface_field_from_expression.py", line 33, in <module>
    shape = shape_mgr.loadAsShape( args.input )
  File "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/7db625a4409c/lib/python2.7/site-packages/icqsol/shapes/icqShapeManager.py", line 245, in loadAsShape
    return self.shapeFromVTKPolyData(vtk_poly_data)
  File "/Users/gvk/work/ts_install/tool_dependency_dir/icqsol/latest/iuc/package_icqsol_latest/7db625a4409c/lib/python2.7/site-packages/icqsol/shapes/icqShapeManager.py", line 322, in shapeFromVTKPolyData
    polygons.append(Polygon(verts))
  File "build/bdist.macosx-10.4-x86_64/egg/csg/geom.py", line 278, in __init__
  File "build/bdist.macosx-10.4-x86_64/egg/csg/geom.py", line 180, in fromPoints
  File "build/bdist.macosx-10.4-x86_64/egg/csg/geom.py", line 96, in unit
  File "build/bdist.macosx-10.4-x86_64/egg/csg/geom.py", line 77, in dividedBy
ZeroDivisionError: float division by zero

[surface_field.txt](https://github.com/pletzer/icqsol/files/2546/surface_field.txt)

**Comment by pletzer** [comment]
The problem was due to some polygons having near zero area. I fixed the shapeFromVtkPolyData method by filtering the incoming polydata through a vtkCleanPolyData filter. Also, I added a new unit test: 

1/1 Test #35: testAddSurfaceFieldFromExpressionSmallPolygon ...   Passed    0.55 sec

The following tests passed:
	testAddSurfaceFieldFromExpressionSmallPolygon

100% tests passed, 0 tests failed out of 1

**Comment by gregvonkuster** [comment]
@pletzer In testing this, I've found that adding a surface field to a shape that already has a surface field produces a shape with a single surface field - I assume the first surface field is replaced.  I expected the shape to have 2 surface fields.  Is this expected behavior?

**Comment by pletzer** [comment]
Hi Greg,

I guess it would be better to add a new field to an existing field. Please
open a new ticket to resolve this. Thanks.

--Alex

On Wed, Sep 30, 2015 at 10:42 AM, Greg Von Kuster <notifications@github.com>
wrote:

> @pletzer <https://github.com/pletzer> In testing this, I've found that
> adding a surface field to a shape that already has a surface field produces
> a shape with a single surface field - I assume the first surface field is
> replaced. I expected the shape to have 2 surface fields. Is this expected
> behavior?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pletzer/icqsol/issues/28#issuecomment-144433013>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net
