### ISSUE TITLE
Shape translation and rotation throw exceptions

### ISSUE THREAD

**Issue by gregvonkuster** [pletzer/icqsol#41]
Translation:
Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_translate_shape/dcc07bc85d40/icqsol_translate_shape/icqsol_translate_shape.py", line 36, in <module>
    shape_mgr.translateVtkPolyData(vtk_poly_data, displ=displ)
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 375, in translateVtkPolyData
AttributeError: SetInput

Rotation:
Traceback (most recent call last):
  File "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_rotate_shape/a28bcf5598a8/icqsol_rotate_shape/icqsol_rotate_shape.py", line 40, in <module>
    shape_mgr.rotateVtkPolyData(vtk_poly_data, angleDeg=args.rotation_degrees, axis=axis)
  File "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line 361, in rotateVtkPolyData
AttributeError: SetInput

**Comment by pletzer** [comment]
Should be fixed now (vtk 5 vs 6 issue). Thanks.

On Fri, Dec 4, 2015 at 7:17 AM, Greg Von Kuster <notifications@github.com>
wrote:

> Translation:
> Traceback (most recent call last):
> File
> "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_translate_shape/dcc07bc85d40/icqsol_translate_shape/icqsol_translate_shape.py",
> line 36, in
> shape_mgr.translateVtkPolyData(vtk_poly_data, displ=displ)
> File
> "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line
> 375, in translateVtkPolyData
> AttributeError: SetInput
>
> Rotation:
> Traceback (most recent call last):
> File
> "/Users/gvk/work/ts_install/shed_tools/localhost/repos/iuc/icqsol_rotate_shape/a28bcf5598a8/icqsol_rotate_shape/icqsol_rotate_shape.py",
> line 40, in
> shape_mgr.rotateVtkPolyData(vtk_poly_data, angleDeg=args.rotation_degrees,
> axis=axis)
> File
> "build/bdist.macosx-10.5-x86_64/egg/icqsol/shapes/icqShapeManager.py", line
> 361, in rotateVtkPolyData
> AttributeError: SetInput
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pletzer/icqsol/issues/41>.
>



-- 
Alexander Pletzer
+1 609 799 7999 cell
alexander@gokliya.net

**Comment by gregvonkuster** [comment]
Confirmed.  Thanks!
